[package]
name = "emit"
version = "0.8.0"
authors = ["Nicholas Blumhardt <nblumhardt@nblumhardt.com>"]
description = "An experimental structured event emitter, currently work-in-progress."
license = "Apache-2.0"
homepage = "https://github.com/nblumhardt/emit"

[dependencies]
serde = "0.7"
serde_json = "0.7"
chrono = "0.2"
hyper = "0.8"
log = "0.3"
