[package]
name = "emit"
version = "0.8.1"
authors = ["Nicholas Blumhardt <nblumhardt@nblumhardt.com>"]
description = "A structured event emitter in the style of Serilog."
license = "Apache-2.0"
homepage = "https://github.com/emit-rs/emit"

[dependencies]
serde = "0.7"
serde_json = "0.7"
chrono = "0.2"
hyper = "0.8"
log = "0.3"
