[package]
name = "emit_example_metric_prometheus"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.emit]
version = "0.11.4"
path = "../../"

[dependencies.emit_otlp]
version = "0.11.4"
path = "../../emitter/otlp"

[dependencies.rand]
version = "0.8"
