[package]
name = "emit_otlp_gen"
version = "0.11.0-alpha.8"
publish = false
edition = "2021"

[[bin]]
name = "gen"
path = "main.rs"

[dependencies.prost]
version = "0.12"

[dependencies.prost-build]
version = "0.12"
