[book]
authors = ["emit contributors"]
language = "en"
multilingual = false
src = "src"
title = "emit"

[rust]
edition = "2021"

[build]
build-dir = "./dist"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
