name: all

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "build ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - name: Run tests
      run: cargo test --all --verbose
