name: term

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Rust toolchain
        run: rustup default nightly

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: All
        working-directory: ./emitter/term
        run: cargo test --all-features

      - name: Docs
        working-directory: ./emitter/term
        run: cargo doc --all-features

      - name: Build powerset
        working-directory: ./emitter/term
        run: cargo hack build --feature-powerset --lib

      - name: Test powerset
        working-directory: ./emitter/term
        run: cargo hack test --feature-powerset --lib

      - name: Minimal versions
        working-directory: ./emitter/term
        run: cargo hack test --feature-powerset --lib -Z minimal-versions

  wasip1:
    name: Test (Wasip1)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Wasmtime
        run: curl https://wasmtime.dev/install.sh -sSf | bash

      - name: Add Wasmtime to path
        run: echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Install Rust toolchain
        run: rustup default nightly

      - name: Install wasm32-wasip1 target
        run: rustup target add wasm32-wasip1

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: All
        working-directory: ./emitter/term
        run: cargo test --target wasm32-wasip1 --all-features

      - name: Build powerset
        working-directory: ./emitter/term
        run: cargo hack build --target wasm32-wasip1 --feature-powerset --lib
